version: '3.8'

services:
  # Definimos el servicio de la aplicación con un nombre claro
  app-videojuegos:
    image: nodensx/jenkins:latest
    ports:
      - "5009:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - red-videojuegos-nueva
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  # Usamos la red que ya tienes creada (confirmada en image_1ea27b.png)
  red-videojuegos-nueva:
    external: true
