version: '3.8'

services:
  web-videojuegos-final:
    image: nodensx/videojuegos:v1 # <--- Nombre totalmente nuevo
    ports:
      - "5009:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - red-videojuegos-nueva
    deploy:
      replicas: 1

networks:
  red-videojuegos-nueva:
    external: true
